### ISSUE TITLE
Incorrect signing when a personal field is included in the reply-to 

### ISSUE THREAD

**Issue by wslade64** [markenwerk/java-utils-mail-dkim#11] opened 2018-11-07 20:54 UTC
When a reply-to address is include with a personal field the body hash is incorrect.

new InternetAddress("myname@me.com", " My Name")

If only the reply-to email is included then the hash is correct.

Interestingly when a personal is included on the from then the hash is correct.

**Comment by toKrause** [comment] 2019-10-20 22:15
Sorry, but I couldn't reproduce the behavior.

I've tried various combinations with both header canonicalizations, with and without a personal field and even with and without the leading whitespace character in the personal field.

I used dkimvalidator.com and the DKIM Verifier plugin for Thunderbird to independently check the generated signatures.

I'm closing the issue for the moment. Feel free to reopen it, if you can provide more details on how to recreate the problem. Sorry for the long delay.

**Closed as completed by toKrause** 2019-10-20 22:15 UTC
